In [1]:
import numpy as np
# help(method_name)
# help(max)
# From a Python List or Tuple: You can create a NumPy array from a Python list or tuple using the numpy.array() function.

# NumPy (Numerical Python)

• NumPy is an open source Python library and is written partially in Python,
but most of the parts that require fast computation are written in C or C++.

• It’s the universal standard for working with numerical data in Python, and
it’s at the core of the scientific Python and PyData ecosystems (Numpy,
Scipy, Pandas, Scikit-Learn, etc.)

• It provides ndarray, a homogeneous n-dimensional array object, with
methods to efficiently operate on it.

• NumPy can be used to perform a wide variety of mathematical operations
on arrays. It adds powerful data structures to Python that guarantee
efficient calculations with arrays and matrices and it supplies an enormous
library of high-level mathematical functions that operate on these arrays
and matrices.

• NumPy is a general-purpose array-processing package.

• It provides a high-performance multidimensional array object, and
tools for working with these arrays.

• The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-
learn, scikit-image and most other data science and scientific Python
packages.
• It contains various features including these important ones:
• A powerful N-dimensional array object
• Sophisticated (broadcasting) functions
• Tools for integrating C/C++ and Fortran code
• Useful linear algebra, Fourier transform, and random number capabilities

# Why Use NumPy?

• In Python we have lists that serve the purpose of arrays, but they are
slow to process.

• NumPy aims to provide an array object that is up to 50x faster than
traditional Python lists.

• The Python NumPy array consumes less memory than lists.

• The array object in NumPy is called ndarray, it provides a lot of
supporting functions that make working with ndarray very easy.

• Arrays are very frequently used in data science, where speed and
resources are very important.

In [2]:
my_list = [1, 2, 3, 4, 5]
existing_array = np.array([[1, 2, 3], [4, 5, 6]])
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])



In [3]:
my_array = np.array(my_list)

my_arange_array = np.arange(1, 10, 2) # create an array with a range of elements
my_linspace_array = np.linspace(0, 10, 5) # Create array with linearly spaced values

print(f"np.arange(1, 10, 2) - {my_linspace_array}")
print(f"np.linspace(0, 10, 5) - {my_arange_array}")

np.arange(1, 10, 2) - [ 0.   2.5  5.   7.5 10. ]
np.linspace(0, 10, 5) - [1 3 5 7 9]


In [5]:

zeros_array = np.zeros((3, 3))  # Creates a 3x3 array filled with zeros
ones_array = np.ones((2, 4))     # Creates a 2x4 array filled with ones
my_full_array = np.full((2,2), 7)

print(f"np.zeros((3, 3)) - \n{zeros_array}")
print(f"np.ones((2, 4)) - \n{ones_array}")
print(f"np.full((2,2), 7) - \n{my_full_array}")


np.zeros((3, 3)) - 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
np.ones((2, 4)) - 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
np.full((2,2), 7) - 
[[7 7]
 [7 7]]


In [7]:
# Create array filled with random values

random_array_rand = np.random.rand(3, 3)
random_array_random=np.random.random((3,2))

print(f"np.random.rand(3, 3) - \n{random_array_rand}")
print(f"np.random.random((3,2)) - \n{random_array_random}")

np.random.rand(3, 3) - 
[[0.31632802 0.77479885 0.00221376]
 [0.43269026 0.49060344 0.61257712]
 [0.92771779 0.42178906 0.19961574]]
np.random.random((3,2)) - 
[[0.55696012 0.68159275]
 [0.32944046 0.85694371]
 [0.49262789 0.39979805]]


In [9]:
unique_values = np.unique(a) # work like set
reversed_arr = np.flip(a) # reverse array

print(f"a - {a}")
print(f"np.unique(a) - {unique_values}")
print(f"np.flip(a) - {reversed_arr}")

a - [11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
np.unique(a) - [11 12 13 14 15 16 17 18 19 20]
np.flip(a) - [20 19 18 14 11 13 12 17 16 15 14 13 12 11 11]


In [11]:

new_array = np.array(existing_array, dtype=float)
arr=np.array([12,45.,3.],dtype=complex)

print(f"{arr}")

[12.+0.j 45.+0.j  3.+0.j]


In [14]:
# Identity matrix – all are 2-dimensional
Identity_matrix = np.eye(3)

empty_array=np.empty((2,3)) # Create an Empty array

a=Identity_matrix.__array__(int) #convert the content to int type

print(f"np.empty((2,3)) - \n{empty_array}")
print(f"np.eye((2,3)) - \n{Identity_matrix}")

np.empty((2,3)) - 
[[12.  0. 45.]
 [ 0.  3.  0.]]
np.eye((2,3)) - 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# Reshaping and flattening multidimensional arrays
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"{x}\nflatten - {x.flatten()}")

# But when you use ravel, the changes you make to the new array will affect the parent array.
a2 = x.ravel()

print(f"Original array - {x}")  # Original array
print(a2)  # New array


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [18]:
# sort

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
# You can quickly sort the numbers in ascending order with:
print(f"{arr}")
print(f"np.sort(arr) - {np.sort(arr)}")
# array([1, 2, 3, 4, 5, 6, 7, 8])

"""
In addition to sort, which returns a sorted copy of an array, you can use:

argsort, which is an indirect sort along a specified axis,
lexsort, which is an indirect stable sort on multiple keys,
searchsorted, which will find elements in a sorted array, and partition, which is a partial sort.
"""

[2 1 5 3 7 4 6 8]
np.sort(arr) - [1 2 3 4 5 6 7 8]


'\nIn addition to sort, which returns a sorted copy of an array, you can use:\n\nargsort, which is an indirect sort along a specified axis,\nlexsort, which is an indirect stable sort on multiple keys,\nsearchsorted, which will find elements in a sorted array, and partition, which is a partial sort.\n'

In [23]:
# concatenate
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# np.concatenate((a, b))
print(f"{a}+{b}={np.concatenate((a, b))}\n")


x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

# np.concatenate((x, y), axis=0)
print(f"{x}\n+\n{y}\n\n{np.concatenate((x, y), axis=0)}")


[1 2 3 4]+[5 6 7 8]=[1 2 3 4 5 6 7 8]

[[1 2]
 [3 4]]
+
[[5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [24]:
# Can you reshape an array?
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim
array_example.size # 24
array_example.shape # (3, 2, 4)

a = np.arange(6)
print(a)

b = a.reshape(3, 2)
print(b)

np.reshape(a, newshape=(1, 6), order='C')
# array([[0, 1, 2, 3, 4, 5]])
"""
a is the array to be reshaped.
"""
"""
newshape is the new shape you want. You can specify an integer or a tuple of integers. 
If you specify an integer, the result will be an array of that length.
The shape should be compatible with the original shape.
"""
"""
order: C means to read/write the elements using C-like index order, 
F means to read/write the elements using Fortran-like index order, 
A means to read/write the elements in Fortran-like index order if 
a is Fortran contiguous in memory, C-like order otherwise. 
(This is an optional parameter and doesn’t need to be specified.)
"""

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


'\norder: C means to read/write the elements using C-like index order, \nF means to read/write the elements using Fortran-like index order, \nA means to read/write the elements in Fortran-like index order if \na is Fortran contiguous in memory, C-like order otherwise. \n(This is an optional parameter and doesn’t need to be specified.)\n'

In [26]:
# Attributes of numpy array
a = np.array([[1,2,3],[4,5,6]])
shape= a.shape
reshape= a.reshape(3,2)
ndim=a.ndim
dtype=a.dtype
itemsize=a.itemsize #This array attribute returns the length of each element of array in bytes.
size=a.size
T=a.T

print(f"{a}")
print(f"a.shape = {shape}")
print(f"reshape = \n{reshape}")
print(f"a.ndim = {ndim}")
print(f"a.dtype = {dtype}")
print(f"a.itemsize = {itemsize}")
print(f"a.size = {size}")
print(f"a.T = \n{T}")


[[1 2 3]
 [4 5 6]]
a.shape = (2, 3)
reshape = 
[[1 2]
 [3 4]
 [5 6]]
a.ndim = 2
a.dtype = int64
a.itemsize = 8
a.size = 6
a.T = 
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# NumPy Array Indexing


In [ ]:
# Slicing arrays

In [ ]:
# Data Types in NumPy

i4 = np.array([1, 2, 3, 4], dtype='i4')  # dtype('int32')
int32 = np.array([1, 2, 3, 4], dtype='int32')  # dtype('int32')
uint = np.array([1111, 24, 333, 41],dtype='uint')  # unsigned int

bool = np.array([1, 0, 3],dtype='bool' )

float=np.array([1,2.2,3.,40],dtype=float)
float32=np.array([1,2.2,3.,40],dtype='float32')

complex=np.array([12+2j,45.,3.],dtype=complex)

Unicode = np.array(['C++', 'Python', 'Java']) #dtype('<U6’) #Unicode string of maximum length 6
arr = np.array(['C++', 'Python', 'Java'],dtype='U')
String = np.array([11, 24, 333, 41], dtype='S' ) #’S’ means String

# if a Value Can Not Be Converted to the mentioned datatype
• If a type is given in which elements can't be casted then NumPy will
raise a ValueError.
# ValueError: In Python ValueError is raised when the type of passed
argument to a function is unexpected/incorrect.

>>> arr = np.array(['a', '2', '3'], dtype='i')
Traceback (most recent call last):
File "<pyshell#9>", line 1, in <module>
arr = np.array(['a', '2', '3'], dtype='i')
ValueError: invalid literal for int() with base 10: 'a'

In [27]:
# Converting Data Type on Existing Arrays
arr = np.array([1.1, 2.8, 3.1])
arr.dtype

newarr = arr.astype('i')
newarr

newarr = arr.astype('int')
newarr.dtype

arr = np.array([1, 0, 3])
newarray=arr.astype(bool)

# numpy Aggregate Functions

# np.mean()
  Compute the arithmetic mean along the specified axis.

# np.std()
  Compute the standard deviation along the specified axis.

# np.var()
  Compute the variance along the specified axis.

# np.sum()
  Sum of array elements over a given axis.

# np.prod()
  Return the product of array elements over a given axis.

# np.cumsum()
  Return the cumulative sum of the elements along a given axis.

# np.cumprod()
  Return the cumulative product of elements along a given axis.

# np.min(), np.max()
  Return the minimum / maximum of an array or minimum along an axis.

# np.argmin(), np.argmax()
  Returns the indices of the minimum / maximum values along an axis

# np.all()
  Test whether all array elements along a given axis evaluate to True.

# np.any()
  Test whether any array element along a given axis evaluates to True.

# np.median()
  Compute the median along the specified axis.

In [28]:
#  sum(), mean() and var()

arr2 = np.array([[0, 10, 20], [30, 40, 50], [60, 70, 80]])
arr2.shape
arr2.ndim

#axis 0 means column
#axis 1 means row

arr2.sum()
arr2.sum(axis=0)
arr2.sum(axis=1)

arr2.mean()
np.mean(arr2,axis=0)

arr.std() # standard deviation
arr.var()


1.5555555555555556

In [29]:
arr2 = np.array([[0, 10, 20], [30, 40, 50], [60, 70, 80]])

arr2.cumsum()
arr2.cumsum(axis=0)
arr2.cumsum(axis=1)


array([[  0,  10,  30],
       [ 30,  70, 120],
       [ 60, 130, 210]])

In [30]:
# prod() and cumprod()
arr2 = np.array([[0, 10, 20], [30, 40, 50], [60, 70, 80]])

arr2.prod(axis=1)
arr2.cumprod(axis=1)
arr2.cumprod(axis=0)

array([[    0,    10,    20],
       [    0,   400,  1000],
       [    0, 28000, 80000]])

In [31]:
# min()
arr2 = np.array([[0, 10, 20], [30, 40, 50], [60, 70, 80]])
arr2.min()
arr2.min(0)
arr2.min(axis=1)

array([ 0, 30, 60])

In [32]:
# max()
arr2 = np.array([[0, 10, 20], [30, 40, 50], [60, 70, 80]])
arr2.max(0)
arr2.max(1)

array([20, 50, 80])

In [33]:
# argmax() and argmin()

arr2 = np.array([[100, 500, 55], [30, 40, 50], [600, 70, 80]])

np.argmax(arr2)
np.argmax(arr2,axis=0)
np.argmax(arr2,axis=1)

np.argmin(arr2)
np.argmin(arr2,axis=0)
np.argmin(arr2,axis=1)


array([2, 0, 1])

In [34]:
# any() and all()

arr2 = np.array([[0, 500, 55], [30, 40, 50], [600, 70, 80]])
np.any(arr2)
np.all(arr2)

np.any(arr2,axis=0)
np.any(arr2,axis=1)


np.all(arr2,axis=0)
np.all(arr2,axis=1)


array([False,  True,  True])

In [ ]:
# median()
np.median(arr2)
np.median(arr2,axis=0)


# Element-wise Operations

# np.add(), np.subtract(),np.multiply(), np.divide()  
Addition, subtraction, multiplication, and division of arguments(NumPy arrays) element-wise.

# np.power()   
First array elements raised to powers from second array, element-wise.

# np.remainder()
Return element-wise remainder of division.

# np.reciprocal()
Return the reciprocal of the argument, element-wise.

# np.sign(), np.abs()
Return sign and the absolute value.

# np.floor(), np.ceil()
Return the floor, ceiling of the input, element-wise.

# np.round()
Round a number to a given precision in decimal digits (default 0 digits).

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.int32)
y = np.array([[5,6],[7,8]], dtype=np.int32)

np.add(x, y)
x+y

x*y
np.multiply(x,y)

x/y 
np.divide(x,y)

np.power(x,y)

x%y
np.remainder(x,y)

np.reciprocal(a)
np.sign(a)
np.abs(a)
np.floor(a)
np.ceil(a)
np.round(a,3)
np.sqrt(y)

In [ ]:
# Other element-wise operations : Python numpy Array maximum / minimum

a = np.array([1, 20, 5, 22, 8, 15])
b = np.array([12, 9, 3, 42, 6, 33])

np.maximum(a,b)
np.minimum(a,b)

# Other element-wise operations : Logical operations

a = np.array([5, 2, 0, 0], dtype=bool)
b = np.array([11, 0, 7, 0], dtype=bool)

np.logical_or(a,b)
np.logical_and(a,b)

# Other element-wise operations : Comparisons

a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])


a==b
a!=b
a>b
a<b
a>=b
a<=b



In [ ]:
# Array-wise comparisons : (element-wise output is not produced)

a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a,b)
np.array_equal(a,c)

# Other operations : dot product

x=np.array([1,2,3,4])
y=np.array([2,2,3,3])
np.dot(x,y)

a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
np.dot(a,b)

# How to save and load NumPy objects
a = np.array([1, 2, 3, 4, 5, 6])
np.save('filename', a)
b = np.load('filename.npy')

csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt('new_file.csv', csv_arr)
np.loadtxt('new_file.csv')

In [ ]:
# Importing and exporting a CSV

import pandas as pd

# If all of your columns are the same type:
x = pd.read_csv('music.csv', header=0).values
print(x)

# You can also simply select the columns you need:
x = pd.read_csv('music.csv', usecols=['Artist', 'Plays']).values
print(x)

a = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]])
df = pd.DataFrame(a)
print(df)
df.to_csv('pd.csv')

data = pd.read_csv('pd.csv')
np.savetxt('np.csv', a, fmt='%.2f', delimiter=',', header='1,  2,  3,  4')